version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - data-postgresql:/var/lib/postgresql
    networks:
      - specialnetwork # HUZZAH!! Explicitly putting this on the same network made things work. Got rid of "PG-CONNECTION BAD error"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: password
  backend:
    build: ../RubyMineProjects/ruby-trial-project
    container_name: ruby-container
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    ports:
      - "3001:3001"
    networks:
      - specialnetwork
    depends_on:
      - db
  client:
    container_name: react-container
    environment:
      CHOKIDAR_USEPOLLING: "true" # note that this ups the CPU usage
    build:
      context: ../react-docker-app
    networks:
      - specialnetwork
    ports:
      - 3000:3000
volumes:
  data-postgresql:
    external: true

networks:
  specialnetwork:
    driver: bridge